### ISSUE TITLE
ValueError: Floating point image RGB values must be in the 0..1 range.

### ISSUE THREAD

**Issue by JingyunLiang** [assafshocher/BlindSR_dataset_generator#1]
Due to `raw_kernel_centered = kernel_shift(raw_kernel, scale_factor)` in kernel generation, sometimes, some entrys of the kernel are negative. Thus, after downscaling, some pixel values may be smaller than 0. When saving the image, it outputs `ValueError: Floating point image RGB values must be in the 0..1 range.` 

This happens randomly, but for the generation of DIV2KRK, there are nearly always errors. 

How do you deal with this problem?

**Comment by assafshocher** [comment]
We have not seen this happening.
Note that negative values are perfectly fine for the kernel  (for example, bicubic kernel has negative values).
What are the negative values you got? are they very close to 0? If so I can simply add clipping right before saving the image

**Comment by JingyunLiang** [comment]
Yes, they are close to 0. The detail is as follows:
```
raw_kernel 9.587125686114092e-18 0.9741281937469759
raw_kernel_centered -0.0008175844422140284 0.9217544655282135
kernel -4.4813746597444796e-05 0.05052355317743564
lr -4.6444268e-07 0.9028595
```
I will clip the negative values to [0,1]. Thank you.

**Comment by assafshocher** [comment]
Clip the image, not the kernel

**Comment by JingyunLiang** [comment]
For sure, I use `np.clip(lr, 0, 1)` instead of `lr` in plt.imsave().
